const live = {
    teamNames: {
        abbreviatedName: 'S.P.B.C.',
        fullName: 'Stanningley Park Bowling Club',
        shortName: 'Stanningley',
    },
    socialLinks: {
        instagramUrl: 'https://www.instagram.com/StanningleyParkBowls',
        facebookUrl: 'https://www.facebook.com/StanningleyBowlsClub',
        emailUrl: 'mailto:stanningleybowlsclub@gmail.com',
        teamPhotosUrl:
            'https://photos.google.com/share/AF1QipMmkXau_XJaD1459y7Sdsk7pSoUeAr04SiVP_z07i1u0NzLiVQLBioFHwGF9jHV_A?key=N3VLT0l0VWZEVlNrVm5kQUF3MHl1d2lJNEFDRVNR',
        historicStatsUrl:
            'https://photos.google.com/share/AF1QipOqs9EK2LBhL3uZjas8l1ccFkrkdsY8KpOlajx60sBsUaM_-S4LCr-qLpEj9aRX3Q?key=N1VwMnRwdWlKQU5pcW9lVXk1b09IX3Y1OGxQWlFR',
        googleMapsUrl: 'https://goo.gl/maps/RQ7wemtuHQhXPgmF9',
        googleMapsIframeUrl:
            'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d739.5172794483534!2d-1.6554462674593056!3d53.81026923756449!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48795fb1c49a2601%3A0xe4eb67d3c4eeb88f!2sStanningley%20Park%20Crown%20Green%20Bowling%20Club!5e0!3m2!1sen!2suk!4v1657105300205!5m2!1sen!2suk',
    },
    membership: {
        socialPrice: '20',
        bowlingPrice: '52',
        bowlingPriceOnly: '10',
        leedsCouncilFee: '42',
    },
    teams: [
        {
            name: 'Monday Combined',
            age: 'Open Age',
            desc: '4 singles games and 2 pairs',
            link: 'https://bowlsnet.uk/Leeds-MonComb',
            startTime: '6:15-6.45pm',
            numberOfGames: 6,
        },
        {
            name: 'Tuesday Vets',
            age: '55+ year olds',
            desc: '8 singles games',
            link: 'https://bowlsnet.uk/Leeds-TueVets',
            startTime: '1:30pm',
            numberOfGames: 8,
        },
        {
            name: 'Tuesday',
            age: 'Open Age',
            desc: '8 singles games',
            link: 'https://bowlsnet.uk/Leeds-Tue',
            startTime: '6:15-6.45pm',
            numberOfGames: 8,
        },
        {
            name: 'Wednesday Half Holiday',
            age: 'Open Age',
            desc: '6 singles games',
            link: 'https://bowlsnet.uk/Leeds-Wed',
            startTime: '1:30pm',
            numberOfGames: 6,
        },
        {
            name: 'Wednesday Pairs',
            age: 'Open Age',
            desc: '4 pairs games',
            link: 'https://bowlsnet.uk/AW-WedPairs',
            startTime: '6:15-7pm',
            numberOfGames: 4,
        },
        {
            name: 'Thursday Vets',
            age: '55+ year olds',
            desc: '8 singles games',
            link: 'https://bowlsnet.uk/leeds-ThuVets',
            startTime: '1:30pm',
            numberOfGames: 8,
        },
        {
            name: 'Saturday',
            age: 'Open Age',
            desc: '8 singles games',
            link: 'https://bowlsnet.uk/Leeds-Sat',
            startTime: '2pm',
            numberOfGames: 8,
        },
    ],
    days: {
        'monday combined leeds': 'Monday Combined',
        'tuesday vets leeds': 'Tuesday Vets',
        'tuesday leeds': 'Tuesday',
        'wednesday half holiday leeds': 'Wednesday Half Holiday',
        'wednesday pairs airewharfe': 'Wednesday Pairs',
        'thursday vets leeds': 'Thursday Vets',
        'saturday leeds': 'Saturday',
        'saturday leeds (b)': 'Saturday B',
    },
    leagues: 'Leeds',
    allTeamsInLeaguesSince2013: [
        'monday combined leeds',
        'monday airedale & wharfedale',
        'monday airedale & wharfedale (a)',
        'monday airedale & wharfedale (b)',
        'tuesday vets leeds',
        'tuesday leeds',
        'wednesday half holiday leeds',
        'wednesday half holiday bradford',
        'wednesday half holiday bradford (a)',
        'wednesday half holiday bradford (b)',
        'wednesday pairs airewharfe',
        'wednesday pairs airewharfe (a)',
        'wednesday pairs airewharfe (b)',
        'thursday vets leeds',
        'thursday vets leeds (a)',
        'thursday vets leeds (b)',
        'saturday leeds',
        'saturday leeds (a)',
        'saturday leeds (b)',
        'saturday bradford',
        'saturday bradford (a)',
        'saturday bradford (b)',
    ],
};

export default live;
