# Team info (lowercase)
stanningleyTeamNames = ['stanningley', 'stanningley a',
                        'stanningley park', 'stanningley park a']

# Days played
stanningleyTeamDays = ['Monday', 'Tuesday', 'Thursday', 'Saturday']

# Every Stanningley player (lowercase)
stanningleyPlayers = [
    'jeff allman', 'shirley allman', 'john armitage', 'mario biancardo', 'shirley biancardo',
    'paul bowes', 'clifford brogie', 'craig clarkson', 'steve gardner', 'andy marshall', 'bernie miller',
    'alyssa randell', 'andy waller', 'kevin waller', 'jim moorin', 'duncan mcphail', 'stewart watson',
    'dave hudson', 'neil porter', 'donald shaw', 'alison woodfine', 'joey broadbent', 'jack roberts', 'vanessa lancaster'
]

# Stanningley players with different spellings of name (lowercase)
duplicateTeamMemberNames = ['duncan mc phail',
                            'stuart watson', 'andrew marshall']

traitorPlayers = {
    'Monday': [],
    'Tuesday': [],
    'Thursday': ['mario biancardo', 'shirley biancardo'],
    'Saturday': ['mario biancardo', 'shirley biancardo', 'dave hudson', 'clifford brogie'],
}

# Base information for each player. New players need adding to this
stanningleyPlayerResults = {
    'jim moorin': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'duncan mcphail': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'stewart watson': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'dave hudson': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'donald shaw': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'alison woodfine': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'joey broadbent': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'neil porter': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'jack roberts': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'jeff allman': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'shirley allman': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'john armitage': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'mario biancardo': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'shirley biancardo': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'paul bowes': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'clifford brogie': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'craig clarkson': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'steve gardner': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'andy marshall': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'alyssa randell': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'andy waller': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'kevin waller': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'Vanessa Lancaster': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
    'bernie miller': {
        'totalScore': 0,
        'totalAgg': 0,
        'totalScoreAgainst': 0,
        'totalAggAgainst': 0,
        'homeWins': 0,
        'homeLosses': 0,
        'awayWins': 0,
        'awayLosses': 0,
        'pairWins': 0,
        'pairLosses': 0,
        'pairsPartners': [],
        'beatenOpponents': [],
        'beatenBy': [],
        'dayPlayed': [],
        'totalPairsAgg': 0,
        'totalPairsAggAgainst': 0,
        'winningPairsPartners': [],
        'losingPairsPartners': [],
        'totalHomeAgg': 0,
        'totalHomeAggAgainst': 0,
        'totalAwayAgg': 0,
        'totalAwayAggAgainst': 0,
        'totalHomeScore': 0,
        'totalHomeScoreAgainst': 0,
        'totalAwayScore': 0,
        'totalAwayScoreAgainst': 0,
        'cupWins': 0,
        'cupLosses': 0,
        'beatenTeam': [],
        'beatenByTeam': [],
        'monday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'tuesday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'thursday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
        'saturday': {
            'games': 0,
            'wins': 0,
            'aggDiff': 0,
        },
    },
}
