name: Run UI Tests on PR
on:
    workflow_dispatch:
    pull_request:
        branches:
            - master
jobs:
    Run-Tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@master
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: |
                  npm ci
                  npx playwright install-deps
                  npx playwright install
            - name: Run tests
              run: npm run tests
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: test-results
                  path: test-results/
                  retention-days: 1
