name: Run UI Tests
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: | 
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Run tests
        run: npm run tests
