name: Update stats
on:
  # TODO add this in
  # schedule:
    # Runs on Mon, Tue, Wed, Thu, and Sat from April 1st to September 30th at 10 PM (UTC time)
    # - cron: '0 22 1-30 4-9 1,2,3,4,6'
  # TODO remove this once working
  push:
    branches:
      - '*'
  workflow_dispatch:
    # TODO workflow dispatch not working?
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: | 
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Configure Git
        run: | 
          git config --global user.email "stanningleybowlsclub@gmail.com"
          git config --global user.name "SPBC GitHub Action"
      - name: Update stats and deploy
        run: npm run get-stats-update-deploy
        # TODO do I need this? Need to install gh CLI?
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
