name: Update stats
on:
    schedule:
        # Runs every day from April 1st to September 30th at 22:00 UTC
        - cron: '0 21 1-31 4-9 *'
    workflow_dispatch:

env:
    EMAIL: stanningleybowlsclub@gmail.com
    USERNAME: SPBC GitHub Action

jobs:
    Update-Stats:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: update_stats_prod
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.12.3'
            - name: Set node version
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Configure Git
              run: |
                  git pull
                  git config --global user.email "${{ env.EMAIL }}"
                  git config --global user.name "${{ env.USERNAME }}"
            - name: Install dependencies
              run: |
                  npm ci
                  npx playwright install-deps
                  npx playwright install
            - name: Update stats and deploy
              run: npm run get-stats-and-update
            - name: Commit and push
              run: |
                  git add bowlsnetReports/*
                  git add src/data/*
                  git commit -m 'updated stats'
                  git push
            - name: Create a PR
              run: gh pr create --title "updated stats" --body "Stats updated from pipeline"
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 1
