name: Update stats
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: | 
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Update stats and deploy
        run: npm run get-stats-update-deploy
