# TODO why do the scripts fail the first time?
# TODO check PR is created, then check after merge that my result is vs p hatch, not phil hatch
# TODO check update stats runs at 14:15

name: Update stats
on:
  schedule:
    # Runs every day from April 1st to September 30th at 22:15 UTC
    # TODO remove time of 14:15
    - cron: '15 14,21 1-30 4-9 *'
  workflow_dispatch:
jobs:
  Update-Stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: update_stats_prod
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: | 
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Update stats and deploy
        run: npm run get-stats-and-update
      - name: Configure Git
        run: | 
          git config --global user.email "stanningleybowlsclub@gmail.com"
          git config --global user.name "SPBC GitHub Action"
      - name: Commit and push
        run: |
          git add bowlsnetReports/*
          git add src/data/*
          git commit -m 'updated stats'
          git push
      # TODO don't fail the job if this fails due to it already existing
      - name: Create a PR
        run: gh pr create --title "updated stats" --body "Stats updated from pipeline"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
